### ISSUE TITLE
Should the addon be opinionated about the CI used?

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-addon-migrator#23] opened 2022-02-20 11:06 UTC
I noticed that my migrated app has [/test-app/.github/workflows/ci.yml](https://gitlab.com/michal-bryxi/open-source/ember-intl-changeset-validations/-/merge_requests/123/diffs#58b1718e76741e26d59f8f20bf01c388f96822a9_0_1).

- I don't think it should assume the CI used? 
- OR have an option to not generate it? 
- OR an ability to switch between various CIs?

**Comment by lifeart** [comment] 2022-02-21 13:53
@MichalBryxi looks like it's could be covered in scope of https://github.com/NullVoxPopuli/ember-addon-migrator/issues/20
To be able to write transform for non-default files

**Comment by NullVoxPopuli** [comment] 2022-02-24 03:43
Closing as duplicate of https://github.com/NullVoxPopuli/ember-addon-migrator/issues/22

**Closed by NullVoxPopuli** 2022-02-24 03:43 UTC
